# Generated by Django 3.0.4 on 2020-03-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
